// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// iglm_print_registered_functions
void iglm_print_registered_functions();
RcppExport SEXP _iglm_iglm_print_registered_functions() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    iglm_print_registered_functions();
    return R_NilValue;
END_RCPP
}
// xyz_count_global
arma::vec xyz_count_global(arma::mat z_network, arma::vec x_attribute, arma::vec y_attribute, arma::mat neighborhood, arma::mat overlap, bool directed, std::vector<std::string> terms, int n_actor, std::vector<arma::mat>& data_list, std::vector<double>& type_list, std::string type_x, std::string type_y, double attr_x_scale, double attr_y_scale);
RcppExport SEXP _iglm_xyz_count_global(SEXP z_networkSEXP, SEXP x_attributeSEXP, SEXP y_attributeSEXP, SEXP neighborhoodSEXP, SEXP overlapSEXP, SEXP directedSEXP, SEXP termsSEXP, SEXP n_actorSEXP, SEXP data_listSEXP, SEXP type_listSEXP, SEXP type_xSEXP, SEXP type_ySEXP, SEXP attr_x_scaleSEXP, SEXP attr_y_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type z_network(z_networkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_attribute(x_attributeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_attribute(y_attributeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< int >::type n_actor(n_actorSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat>& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type type_list(type_listSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_x(type_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_y(type_ySEXP);
    Rcpp::traits::input_parameter< double >::type attr_x_scale(attr_x_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type attr_y_scale(attr_y_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(xyz_count_global(z_network, x_attribute, y_attribute, neighborhood, overlap, directed, terms, n_actor, data_list, type_list, type_x, type_y, attr_x_scale, attr_y_scale));
    return rcpp_result_gen;
END_RCPP
}
// xyz_simulate_cpp
List xyz_simulate_cpp(arma::vec& coef, arma::vec& coef_popularity, std::vector<std::string>& terms, int& n_actor, arma::mat z_network, arma::mat neighborhood, arma::mat overlap, arma::vec x_attribute, arma::vec y_attribute, bool init_empty, bool directed, bool popularity, std::vector<arma::mat>& data_list, std::vector<double>& type_list, double offset_nonoverlap, std::string type_x, std::string type_y, double attr_x_scale, double attr_y_scale, int n_proposals_x, int seed_x, int n_proposals_y, int seed_y, int n_proposals_z, int seed_z, int n_proposals_z_nonoverlap, int seed_z_nonoverlap, int n_burn_in, int n_simulation, bool only_stats, bool display_progress, bool fix_x);
RcppExport SEXP _iglm_xyz_simulate_cpp(SEXP coefSEXP, SEXP coef_popularitySEXP, SEXP termsSEXP, SEXP n_actorSEXP, SEXP z_networkSEXP, SEXP neighborhoodSEXP, SEXP overlapSEXP, SEXP x_attributeSEXP, SEXP y_attributeSEXP, SEXP init_emptySEXP, SEXP directedSEXP, SEXP popularitySEXP, SEXP data_listSEXP, SEXP type_listSEXP, SEXP offset_nonoverlapSEXP, SEXP type_xSEXP, SEXP type_ySEXP, SEXP attr_x_scaleSEXP, SEXP attr_y_scaleSEXP, SEXP n_proposals_xSEXP, SEXP seed_xSEXP, SEXP n_proposals_ySEXP, SEXP seed_ySEXP, SEXP n_proposals_zSEXP, SEXP seed_zSEXP, SEXP n_proposals_z_nonoverlapSEXP, SEXP seed_z_nonoverlapSEXP, SEXP n_burn_inSEXP, SEXP n_simulationSEXP, SEXP only_statsSEXP, SEXP display_progressSEXP, SEXP fix_xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type coef_popularity(coef_popularitySEXP);
    Rcpp::traits::input_parameter< std::vector<std::string>& >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< int& >::type n_actor(n_actorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_network(z_networkSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_attribute(x_attributeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_attribute(y_attributeSEXP);
    Rcpp::traits::input_parameter< bool >::type init_empty(init_emptySEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< bool >::type popularity(popularitySEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat>& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type type_list(type_listSEXP);
    Rcpp::traits::input_parameter< double >::type offset_nonoverlap(offset_nonoverlapSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_x(type_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_y(type_ySEXP);
    Rcpp::traits::input_parameter< double >::type attr_x_scale(attr_x_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type attr_y_scale(attr_y_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type n_proposals_x(n_proposals_xSEXP);
    Rcpp::traits::input_parameter< int >::type seed_x(seed_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_proposals_y(n_proposals_ySEXP);
    Rcpp::traits::input_parameter< int >::type seed_y(seed_ySEXP);
    Rcpp::traits::input_parameter< int >::type n_proposals_z(n_proposals_zSEXP);
    Rcpp::traits::input_parameter< int >::type seed_z(seed_zSEXP);
    Rcpp::traits::input_parameter< int >::type n_proposals_z_nonoverlap(n_proposals_z_nonoverlapSEXP);
    Rcpp::traits::input_parameter< int >::type seed_z_nonoverlap(seed_z_nonoverlapSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn_in(n_burn_inSEXP);
    Rcpp::traits::input_parameter< int >::type n_simulation(n_simulationSEXP);
    Rcpp::traits::input_parameter< bool >::type only_stats(only_statsSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< bool >::type fix_x(fix_xSEXP);
    rcpp_result_gen = Rcpp::wrap(xyz_simulate_cpp(coef, coef_popularity, terms, n_actor, z_network, neighborhood, overlap, x_attribute, y_attribute, init_empty, directed, popularity, data_list, type_list, offset_nonoverlap, type_x, type_y, attr_x_scale, attr_y_scale, n_proposals_x, seed_x, n_proposals_y, seed_y, n_proposals_z, seed_z, n_proposals_z_nonoverlap, seed_z_nonoverlap, n_burn_in, n_simulation, only_stats, display_progress, fix_x));
    return rcpp_result_gen;
END_RCPP
}
// pl_estimation
List pl_estimation(arma::vec coef, arma::mat z_network, arma::vec x_attribute, arma::vec y_attribute, arma::mat neighborhood, arma::mat overlap, bool directed, std::vector<std::string> terms, std::vector<arma::mat>& data_list, std::vector<double>& type_list, bool display_progress, int max_iteration, double tol, double offset_nonoverlap, bool non_stop, bool fix_x, std::string attr_x_type, std::string attr_y_type, double attr_x_scale, double attr_y_scale);
RcppExport SEXP _iglm_pl_estimation(SEXP coefSEXP, SEXP z_networkSEXP, SEXP x_attributeSEXP, SEXP y_attributeSEXP, SEXP neighborhoodSEXP, SEXP overlapSEXP, SEXP directedSEXP, SEXP termsSEXP, SEXP data_listSEXP, SEXP type_listSEXP, SEXP display_progressSEXP, SEXP max_iterationSEXP, SEXP tolSEXP, SEXP offset_nonoverlapSEXP, SEXP non_stopSEXP, SEXP fix_xSEXP, SEXP attr_x_typeSEXP, SEXP attr_y_typeSEXP, SEXP attr_x_scaleSEXP, SEXP attr_y_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_network(z_networkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_attribute(x_attributeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_attribute(y_attributeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat>& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type type_list(type_listSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type max_iteration(max_iterationSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type offset_nonoverlap(offset_nonoverlapSEXP);
    Rcpp::traits::input_parameter< bool >::type non_stop(non_stopSEXP);
    Rcpp::traits::input_parameter< bool >::type fix_x(fix_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type attr_x_type(attr_x_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type attr_y_type(attr_y_typeSEXP);
    Rcpp::traits::input_parameter< double >::type attr_x_scale(attr_x_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type attr_y_scale(attr_y_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(pl_estimation(coef, z_network, x_attribute, y_attribute, neighborhood, overlap, directed, terms, data_list, type_list, display_progress, max_iteration, tol, offset_nonoverlap, non_stop, fix_x, attr_x_type, attr_y_type, attr_x_scale, attr_y_scale));
    return rcpp_result_gen;
END_RCPP
}
// pl_estimation_old
List pl_estimation_old(arma::vec coef, arma::mat z_network, arma::vec x_attribute, arma::vec y_attribute, arma::mat neighborhood, arma::mat overlap, bool directed, std::vector<std::string> terms, std::vector<arma::mat>& data_list, std::vector<double>& type_list, bool display_progress, int max_iteration, double tol, double offset_nonoverlap, bool non_stop, bool fix_x, std::string attr_x_type, std::string attr_y_type, double attr_x_scale, double attr_y_scale);
RcppExport SEXP _iglm_pl_estimation_old(SEXP coefSEXP, SEXP z_networkSEXP, SEXP x_attributeSEXP, SEXP y_attributeSEXP, SEXP neighborhoodSEXP, SEXP overlapSEXP, SEXP directedSEXP, SEXP termsSEXP, SEXP data_listSEXP, SEXP type_listSEXP, SEXP display_progressSEXP, SEXP max_iterationSEXP, SEXP tolSEXP, SEXP offset_nonoverlapSEXP, SEXP non_stopSEXP, SEXP fix_xSEXP, SEXP attr_x_typeSEXP, SEXP attr_y_typeSEXP, SEXP attr_x_scaleSEXP, SEXP attr_y_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_network(z_networkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_attribute(x_attributeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_attribute(y_attributeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat>& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type type_list(type_listSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type max_iteration(max_iterationSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type offset_nonoverlap(offset_nonoverlapSEXP);
    Rcpp::traits::input_parameter< bool >::type non_stop(non_stopSEXP);
    Rcpp::traits::input_parameter< bool >::type fix_x(fix_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type attr_x_type(attr_x_typeSEXP);
    Rcpp::traits::input_parameter< std::string >::type attr_y_type(attr_y_typeSEXP);
    Rcpp::traits::input_parameter< double >::type attr_x_scale(attr_x_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type attr_y_scale(attr_y_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(pl_estimation_old(coef, z_network, x_attribute, y_attribute, neighborhood, overlap, directed, terms, data_list, type_list, display_progress, max_iteration, tol, offset_nonoverlap, non_stop, fix_x, attr_x_type, attr_y_type, attr_x_scale, attr_y_scale));
    return rcpp_result_gen;
END_RCPP
}
// invert_mat
arma::mat invert_mat(double diag, double offdiag, int n_actor);
RcppExport SEXP _iglm_invert_mat(SEXP diagSEXP, SEXP offdiagSEXP, SEXP n_actorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type diag(diagSEXP);
    Rcpp::traits::input_parameter< double >::type offdiag(offdiagSEXP);
    Rcpp::traits::input_parameter< int >::type n_actor(n_actorSEXP);
    rcpp_result_gen = Rcpp::wrap(invert_mat(diag, offdiag, n_actor));
    return rcpp_result_gen;
END_RCPP
}
// get_A_inv
arma::mat get_A_inv(double n_actor);
RcppExport SEXP _iglm_get_A_inv(SEXP n_actorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type n_actor(n_actorSEXP);
    rcpp_result_gen = Rcpp::wrap(get_A_inv(n_actor));
    return rcpp_result_gen;
END_RCPP
}
// outerloop_estimation_pl
List outerloop_estimation_pl(arma::vec coef, arma::vec coef_popularity, arma::mat z_network, arma::vec x_attribute, arma::vec y_attribute, arma::mat neighborhood, arma::mat overlap, bool directed, std::vector<std::string> terms, std::vector<arma::mat>& data_list, std::vector<double>& type_list, bool display_progress, int max_iteration_outer, int max_iteration_inner_popularity, int max_iteration_inner_nonpopularity, double tol, double offset_nonoverlap, bool non_stop, bool var, bool accelerated, bool fix_x, std::string type_x, std::string type_y, double attr_x_scale, double attr_y_scale, int start);
RcppExport SEXP _iglm_outerloop_estimation_pl(SEXP coefSEXP, SEXP coef_popularitySEXP, SEXP z_networkSEXP, SEXP x_attributeSEXP, SEXP y_attributeSEXP, SEXP neighborhoodSEXP, SEXP overlapSEXP, SEXP directedSEXP, SEXP termsSEXP, SEXP data_listSEXP, SEXP type_listSEXP, SEXP display_progressSEXP, SEXP max_iteration_outerSEXP, SEXP max_iteration_inner_popularitySEXP, SEXP max_iteration_inner_nonpopularitySEXP, SEXP tolSEXP, SEXP offset_nonoverlapSEXP, SEXP non_stopSEXP, SEXP varSEXP, SEXP acceleratedSEXP, SEXP fix_xSEXP, SEXP type_xSEXP, SEXP type_ySEXP, SEXP attr_x_scaleSEXP, SEXP attr_y_scaleSEXP, SEXP startSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_popularity(coef_popularitySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_network(z_networkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_attribute(x_attributeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_attribute(y_attributeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat>& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type type_list(type_listSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< int >::type max_iteration_outer(max_iteration_outerSEXP);
    Rcpp::traits::input_parameter< int >::type max_iteration_inner_popularity(max_iteration_inner_popularitySEXP);
    Rcpp::traits::input_parameter< int >::type max_iteration_inner_nonpopularity(max_iteration_inner_nonpopularitySEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type offset_nonoverlap(offset_nonoverlapSEXP);
    Rcpp::traits::input_parameter< bool >::type non_stop(non_stopSEXP);
    Rcpp::traits::input_parameter< bool >::type var(varSEXP);
    Rcpp::traits::input_parameter< bool >::type accelerated(acceleratedSEXP);
    Rcpp::traits::input_parameter< bool >::type fix_x(fix_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_x(type_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_y(type_ySEXP);
    Rcpp::traits::input_parameter< double >::type attr_x_scale(attr_x_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type attr_y_scale(attr_y_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    rcpp_result_gen = Rcpp::wrap(outerloop_estimation_pl(coef, coef_popularity, z_network, x_attribute, y_attribute, neighborhood, overlap, directed, terms, data_list, type_list, display_progress, max_iteration_outer, max_iteration_inner_popularity, max_iteration_inner_nonpopularity, tol, offset_nonoverlap, non_stop, var, accelerated, fix_x, type_x, type_y, attr_x_scale, attr_y_scale, start));
    return rcpp_result_gen;
END_RCPP
}
// xyz_approximate_variability
List xyz_approximate_variability(arma::vec& coef, arma::vec& coef_popularity, std::vector<std::string>& terms, int& n_actor, arma::mat z_network, arma::mat neighborhood, arma::mat overlap, arma::vec y_attribute, arma::vec x_attribute, bool init_empty, bool directed, std::vector<arma::mat>& data_list, std::vector<double>& type_list, int n_proposals_x, int seed_x, int n_proposals_y, int seed_y, int n_proposals_z, int seed_z, int n_burn_in, int n_simulation, bool display_progress, bool popularity, double offset_nonoverlap, bool return_samples, bool fix_x, bool updated_uncertainty, bool exact, std::string type_x, std::string type_y, double attr_x_scale, double attr_y_scale);
RcppExport SEXP _iglm_xyz_approximate_variability(SEXP coefSEXP, SEXP coef_popularitySEXP, SEXP termsSEXP, SEXP n_actorSEXP, SEXP z_networkSEXP, SEXP neighborhoodSEXP, SEXP overlapSEXP, SEXP y_attributeSEXP, SEXP x_attributeSEXP, SEXP init_emptySEXP, SEXP directedSEXP, SEXP data_listSEXP, SEXP type_listSEXP, SEXP n_proposals_xSEXP, SEXP seed_xSEXP, SEXP n_proposals_ySEXP, SEXP seed_ySEXP, SEXP n_proposals_zSEXP, SEXP seed_zSEXP, SEXP n_burn_inSEXP, SEXP n_simulationSEXP, SEXP display_progressSEXP, SEXP popularitySEXP, SEXP offset_nonoverlapSEXP, SEXP return_samplesSEXP, SEXP fix_xSEXP, SEXP updated_uncertaintySEXP, SEXP exactSEXP, SEXP type_xSEXP, SEXP type_ySEXP, SEXP attr_x_scaleSEXP, SEXP attr_y_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type coef_popularity(coef_popularitySEXP);
    Rcpp::traits::input_parameter< std::vector<std::string>& >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< int& >::type n_actor(n_actorSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type z_network(z_networkSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_attribute(y_attributeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_attribute(x_attributeSEXP);
    Rcpp::traits::input_parameter< bool >::type init_empty(init_emptySEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat>& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type type_list(type_listSEXP);
    Rcpp::traits::input_parameter< int >::type n_proposals_x(n_proposals_xSEXP);
    Rcpp::traits::input_parameter< int >::type seed_x(seed_xSEXP);
    Rcpp::traits::input_parameter< int >::type n_proposals_y(n_proposals_ySEXP);
    Rcpp::traits::input_parameter< int >::type seed_y(seed_ySEXP);
    Rcpp::traits::input_parameter< int >::type n_proposals_z(n_proposals_zSEXP);
    Rcpp::traits::input_parameter< int >::type seed_z(seed_zSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn_in(n_burn_inSEXP);
    Rcpp::traits::input_parameter< int >::type n_simulation(n_simulationSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< bool >::type popularity(popularitySEXP);
    Rcpp::traits::input_parameter< double >::type offset_nonoverlap(offset_nonoverlapSEXP);
    Rcpp::traits::input_parameter< bool >::type return_samples(return_samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type fix_x(fix_xSEXP);
    Rcpp::traits::input_parameter< bool >::type updated_uncertainty(updated_uncertaintySEXP);
    Rcpp::traits::input_parameter< bool >::type exact(exactSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_x(type_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_y(type_ySEXP);
    Rcpp::traits::input_parameter< double >::type attr_x_scale(attr_x_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type attr_y_scale(attr_y_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(xyz_approximate_variability(coef, coef_popularity, terms, n_actor, z_network, neighborhood, overlap, y_attribute, x_attribute, init_empty, directed, data_list, type_list, n_proposals_x, seed_x, n_proposals_y, seed_y, n_proposals_z, seed_z, n_burn_in, n_simulation, display_progress, popularity, offset_nonoverlap, return_samples, fix_x, updated_uncertainty, exact, type_x, type_y, attr_x_scale, attr_y_scale));
    return rcpp_result_gen;
END_RCPP
}
// xyz_prepare_pseudo_estimation
Rcpp::List xyz_prepare_pseudo_estimation(arma::mat z_network, arma::vec x_attribute, arma::vec y_attribute, arma::mat neighborhood, arma::mat overlap, bool directed, std::vector<std::string> terms, std::vector<arma::mat>& data_list, std::vector<double>& type_list, bool display_progress, std::string type_x, std::string type_y, double attr_x_scale, double attr_y_scale, bool return_x, bool return_y, bool return_z);
RcppExport SEXP _iglm_xyz_prepare_pseudo_estimation(SEXP z_networkSEXP, SEXP x_attributeSEXP, SEXP y_attributeSEXP, SEXP neighborhoodSEXP, SEXP overlapSEXP, SEXP directedSEXP, SEXP termsSEXP, SEXP data_listSEXP, SEXP type_listSEXP, SEXP display_progressSEXP, SEXP type_xSEXP, SEXP type_ySEXP, SEXP attr_x_scaleSEXP, SEXP attr_y_scaleSEXP, SEXP return_xSEXP, SEXP return_ySEXP, SEXP return_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type z_network(z_networkSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x_attribute(x_attributeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y_attribute(y_attributeSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type neighborhood(neighborhoodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type overlap(overlapSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< std::vector<arma::mat>& >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<double>& >::type type_list(type_listSEXP);
    Rcpp::traits::input_parameter< bool >::type display_progress(display_progressSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_x(type_xSEXP);
    Rcpp::traits::input_parameter< std::string >::type type_y(type_ySEXP);
    Rcpp::traits::input_parameter< double >::type attr_x_scale(attr_x_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type attr_y_scale(attr_y_scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type return_x(return_xSEXP);
    Rcpp::traits::input_parameter< bool >::type return_y(return_ySEXP);
    Rcpp::traits::input_parameter< bool >::type return_z(return_zSEXP);
    rcpp_result_gen = Rcpp::wrap(xyz_prepare_pseudo_estimation(z_network, x_attribute, y_attribute, neighborhood, overlap, directed, terms, data_list, type_list, display_progress, type_x, type_y, attr_x_scale, attr_y_scale, return_x, return_y, return_z));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iglm_iglm_print_registered_functions", (DL_FUNC) &_iglm_iglm_print_registered_functions, 0},
    {"_iglm_xyz_count_global", (DL_FUNC) &_iglm_xyz_count_global, 14},
    {"_iglm_xyz_simulate_cpp", (DL_FUNC) &_iglm_xyz_simulate_cpp, 32},
    {"_iglm_pl_estimation", (DL_FUNC) &_iglm_pl_estimation, 20},
    {"_iglm_pl_estimation_old", (DL_FUNC) &_iglm_pl_estimation_old, 20},
    {"_iglm_invert_mat", (DL_FUNC) &_iglm_invert_mat, 3},
    {"_iglm_get_A_inv", (DL_FUNC) &_iglm_get_A_inv, 1},
    {"_iglm_outerloop_estimation_pl", (DL_FUNC) &_iglm_outerloop_estimation_pl, 26},
    {"_iglm_xyz_approximate_variability", (DL_FUNC) &_iglm_xyz_approximate_variability, 32},
    {"_iglm_xyz_prepare_pseudo_estimation", (DL_FUNC) &_iglm_xyz_prepare_pseudo_estimation, 17},
    {NULL, NULL, 0}
};

void export_cpp_symbols(DllInfo *dll);
RcppExport void R_init_iglm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    export_cpp_symbols(dll);
}
